# Nombre de la aplicación
spring.application.name=Joyalex18k

# Puerto del servidor
server.port=8081
# Esto permite que se pueda acceder desde cualquier IP de tu red
server.address=0.0.0.0
spring.mvc.cors.allowed-origins=*

# Conexión MySQL (XAMPP)
spring.datasource.url=jdbc:mysql://localhost:3306/Joyalex18k?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# Hibernate y JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.open-in-view=false

# Configuración JSON / MVC
spring.mvc.contentnegotiation.favor-parameter=false
spring.mvc.contentnegotiation.favor-path-extension=false
spring.jackson.serialization.fail-on-empty-beans=false
spring.http.converters.preferred-json-mapper=jackson

# CORS global (opcional pero recomendable si tu frontend corre en otra IP o puerto)
# Esto solo habilita Spring Boot para aceptar peticiones de cualquier origen
# Alternativa: configurar en tu controlador con @CrossOrigin(origins = "*")
# debug=true